const CONTEUDO_DIALOGO_INFO =
"O aplicativo é alimentado com as planílhas de itens presentes nos microdados do ENEM."
"\n\n"
"Toque no título da coluna para alternar entre a ordenação ascendente e descendente."
"\n\n"
"Ao clicar na linha correspondente a um item, será exibido um popup com a descrição "
"da competência e da habilidade desse item."
"\n\n"
"Nesse popup há um botão que permite visualizar um caderno que contenha o item."
"\n\n"
"O aplicativo contém apenas os cadernos de cor cinza, no entanto, ao tocar no "
"referido botão, caso exista, será aberto um caderno de cor cinza que contenha "
"o item."
"\n\n"
"O caderno será exibido diretamente na página que contém o item. Um bunner informando "
"o gabarito e o número do item correspondente será exibido na parte superior."
"\n\n"
"Desenvolvedor: Samy Lourenço."
"\n"
"Contato: professorsamylourenco@gmail.com"
;